"""Layer-1: turn experiment manifests into a forkable lineage DAG."""
from __future__ import annotations

import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))

import argparse
from pathlib import Path

from tools.config import iter_manifests, load_config, repo_root

__all__ = ["champion", "render_mermaid", "render_table", "write_experiments_md",
           "iter_manifests"]


def _passed_repro(m: dict) -> bool:
    repro = m.get("repro") or {}
    return bool(repro.get("byte_identical"))


def _rank_key(m: dict, sign: int = 1):
    """Rank on out-of-fold CV first, leaderboard score as tiebreak.

    CV is the primary signal deliberately. Every experiment has it, measured on
    the same scale, whereas a leaderboard score exists only for the few that were
    submitted -- ranking on LB first lets a submitted-but-worse experiment beat an
    unsubmitted-but-better one. It is also the better proxy for what decides
    placement: the public leaderboard is a minority of the final score in most
    competitions (30% here), and CV estimates generalization rather than fit to
    one public split.

    `sign` is +1 to maximize, -1 to minimize, so the same comparator serves RMSE
    and NDCG alike. Missing values sort last under either direction.
    """
    scores = m.get("scores") or {}
    cv, lb = scores.get("cv_primary"), scores.get("lb_public")
    worst = float("-inf")
    return (sign * cv if cv is not None else worst,
            sign * lb if lb is not None else worst)


def champion(root: Path) -> dict | None:
    eligible = [m for m in iter_manifests(root) if _passed_repro(m)]
    if not eligible:
        return None
    sign = -1 if (load_config(root).get("task") or {}).get("direction") == "minimize" else 1
    return max(eligible, key=lambda m: _rank_key(m, sign))


def _node_id(exp_id: str) -> str:
    return exp_id.replace("-", "")


def _fmt(value, digits: int = 5) -> str:
    return "-" if value is None else f"{value:.{digits}f}"


def render_mermaid(nodes: list[dict], champion_id: str | None) -> str:
    lines = ["graph LR"]
    for m in nodes:
        scores = m.get("scores") or {}
        shown = scores.get("lb_public") if scores.get("lb_public") is not None \
            else scores.get("cv_primary")
        delta = (m.get("delta_vs_parent") or {}).get("lb_public")
        if delta is None:
            delta = (m.get("delta_vs_parent") or {}).get("cv_primary")
        parts = [f"{m['id']} {m['slug']}", _fmt(shown)]
        if delta is not None:
            parts[-1] += f" ({delta:+.5f})"
        if m["id"] == champion_id:
            parts.append("champion")
        if not _passed_repro(m):
            # None means the gate has not been run; False means it ran and failed.
            # A teammate must be able to tell "untested" from "known broken".
            parts.append("REPRO PENDING" if (m.get("repro") or {}).get("byte_identical") is None
                         else "REPRO FAILED")
        label = "<br/>".join(parts)
        lines.append(f'  {_node_id(m["id"])}["{label}"]')
    for m in nodes:
        if m.get("parent"):
            lines.append(f'  {_node_id(m["parent"])} --> {_node_id(m["id"])}')
    return "\n".join(lines)


def render_table(nodes: list[dict], sign: int = 1) -> str:
    header = ("| exp | slug | parent | cv_primary | cv_std | lb_public | repro | reduced |\n"
              "|---|---|---|---|---|---|---|---|")
    rows = []
    for m in sorted(nodes, key=lambda m: _rank_key(m, sign), reverse=True):
        s = m.get("scores") or {}
        r = m.get("repro") or {}
        rows.append(
            f"| {m['id']} | {m['slug']} | {m.get('parent') or '-'} | "
            f"{_fmt(s.get('cv_primary'))} | {_fmt(s.get('cv_std'))} | "
            f"{_fmt(s.get('lb_public'))} | "
            f"{'pass' if r.get('byte_identical') else ('pending' if r.get('byte_identical') is None else 'FAIL')} | "
            f"{'yes' if r.get('reduced_mode') else 'no'} |")
    return "\n".join([header, *rows])


def write_experiments_md(root: Path) -> Path:
    root = Path(root)
    cfg = load_config(root)
    nodes = list(iter_manifests(root))
    champ = champion(root)
    champ_id = champ["id"] if champ else None

    body = [
        "# Experiments",
        "",
        "Generated by `tools/lineage.py` -- do not edit by hand.",
        "",
        f"**Primary metric:** `{cfg['task']['metric']}` ({cfg['task']['direction']})  ",
        f"**Champion:** {champ_id or 'none yet'}",
        "",
        "## Lineage",
        "",
        "Any node is a legal fork point. Dead branches are kept deliberately -- they",
        "are what stops the same idea being re-run by a teammate.",
        "",
        "```mermaid",
        render_mermaid(nodes, champ_id),
        "```",
        "",
        "## Scores",
        "",
        render_table(nodes, -1 if cfg["task"]["direction"] == "minimize" else 1)
        if nodes else "_No experiments yet._",
        "",
    ]
    path = root / "EXPERIMENTS.md"
    path.write_text("\n".join(body), encoding="utf-8")
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate EXPERIMENTS.md.")
    ap.add_argument("--root", default=None)
    args = ap.parse_args()
    root = Path(args.root) if args.root else repo_root()
    print(f"wrote {write_experiments_md(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
